version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - server:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: server

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "rkis"]
  backend:
    


volumes:
  server:
