version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - server:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: server

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "rkis"]
  backend:
    backend:
      build: .
    environment:
      SECRET_KEY: some-secret
      DB: postgresql://njves:ViX8tAxl4Gn67J8kplD9uA8gAC451IM2@dpg-clpv7phjvg7s73e1e8m0-a.frankfurt-postgres.render.com/kursoagregator
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy
volumes:
  server:
