version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - server:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: server
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "rkis"]
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/var/www/html/static
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile

    env_file:
      - .env-development
    environment:
      SECRET_KEY: some-secret
      DB: postgresql://admin:admin@database:5432/server
      CACHE_TYPE: SimpleCache
      CACHE_HOST: localhost

    expose:
      - 5000
    depends_on:
      database:
        condition: service_healthy

volumes:
  server:
